# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=200)),
                ('beskrivelse', models.TextField()),
                ('opprettet_dato', models.DateTimeField(default=django.utils.timezone.now)),
                ('klasse', models.CharField(max_length=10)),
                ('fag', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('eier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
