# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachpack',
            name='mediatype',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
