# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0002_teachpack_mediatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachpack',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teachpack',
            name='mediatype',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('powerpoint', 'PowerPoint'), ('text', 'Text Document'), ('zip', 'Zipped collection')], max_length=200),
        ),
    ]
