# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharestuff', '0003_auto_20161029_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='teachpack',
            name='mediatype',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('powerpoint', 'PowerPoint'), ('text', 'Text Document'), ('zip', 'Zipped collection'), ('www', 'Web')], max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='liker_delt_resurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharestuff.TeachPack'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
