# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0007_auto_20161105_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.CharField(default='normal', max_length=200),
        ),
    ]
