# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharestuff', '0008_profile_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liker_delt_ressurs',
        ),
        migrations.AddField(
            model_name='teachpack',
            name='har_trykt_liker',
            field=models.ManyToManyField(related_name='likertrykker', to=settings.AUTH_USER_MODEL),
        ),
    ]
