# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0009_auto_20161106_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachpack',
            name='har_trykt_liker',
            field=models.ManyToManyField(blank=True, related_name='likertrykker', to=settings.AUTH_USER_MODEL),
        ),
    ]
