# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0010_auto_20161106_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=200)),
                ('hashtag_used', models.ManyToManyField(blank=True, to='sharestuff.TeachPack')),
            ],
        ),
    ]
