# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0011_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag_used',
        ),
    ]
