# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0012_remove_hashtag_hashtag_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='tagget_ressurs',
            field=models.ManyToManyField(blank=True, to='sharestuff.TeachPack'),
        ),
    ]
