# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0014_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachpack',
            name='publish_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
