# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 22:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharestuff', '0015_teachpack_publish_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BjeffeLogg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innhold', models.CharField(max_length=200)),
                ('eier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gruppe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sharestuff.Group')),
            ],
        ),
    ]
