# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0016_bjeffelogg'),
    ]

    operations = [
        migrations.AddField(
            model_name='bjeffelogg',
            name='datotid',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
