# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0017_bjeffelogg_datotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachings',
            field=models.ManyToManyField(blank=True, to='sharestuff.TeachPack'),
        ),
    ]
