# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharestuff', '0018_group_teachings'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='beskrivelse',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
